# REF: https://cloud.google.com/build/docs/deploy-containerized-application-cloud-run
# REF: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions
# REF: https://zenn.dev/jy8752/articles/351fc5d8c53029
# REF: https://cloud.google.com/workflows/docs/deploy-workflows-using-cloud-build
# REF: https://stackoverflow.com/questions/68779751/error-publishing-source-code-from-cloud-build-to-a-bucket-using-triggers
# REF: gcloud builds submit --config cloudbuild.yaml
steps:
  # frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --build-arg
      - PNPM_HOME=${_PNPM_HOME}
      - --build-arg
      - PNPM_PATH=${_PNPM_PATH}
      - --build-arg
      - CLIENT_PORT=${_CLIENT_PORT}
      - --build-arg
      - GRAPHQL_SCHEMA_URL=${_GRAPHQL_SCHEMA_URL}
      - -t
      - ${_FRONTEND_IMAGE}
      - ./frontend
    automapSubstitutions: true

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - ${_FRONTEND_IMAGE}

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image
      - ${_FRONTEND_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated

  # backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --build-arg
      - ENV=${_ENV}
      - --build-arg
      - POSTGRES_USER=${_POSTGRES_USER}
      - --build-arg
      - POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}
      - --build-arg
      - POSTGRES_HOST=${_POSTGRES_HOST}
      - --build-arg
      - POSTGRES_PORT=${_POSTGRES_PORT}
      - --build-arg
      - POSTGRES_DB=${_POSTGRES_DB}
      - --build-arg
      - PORT=${_PORT}
      - -t
      - ${_BACKEND_IMAGE}
      - ./backend
    automapSubstitutions: true

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - ${_BACKEND_IMAGE}

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image
      - ${_BACKEND_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
substitutions:
  # general
  _REGION: _REGION
  # frontend
  _PNPM_HOME: _PNPM_HOME
  _PNPM_PATH: _PNPM_PATH
  _CLIENT_PORT: _CLIENT_PORT
  _GRAPHQL_SCHEMA_URL: _GRAPHQL_SCHEMA_URL
  _FRONTEND_IMAGE: _FRONTEND_IMAGE

  # backend
  _ENV: _ENV
  _POSTGRES_USER: _POSTGRES_USER
  _POSTGRES_PASSWORD: _POSTGRES_PASSWORD
  _POSTGRES_HOST: _POSTGRES_HOST
  _POSTGRES_PORT: _POSTGRES_PORT
  _POSTGRES_DB: _POSTGRES_DB
  _PORT: _PORT
  _BACKEND_IMAGE: _BACKEND_IMAGE
  _BACKEND_SERVICE: _BACKEND_SERVICE

options:
  logging: CLOUD_LOGGING_ONLY
