# REF: https://cloud.google.com/build/docs/deploy-containerized-application-cloud-run
# REF: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions
# REF: https://zenn.dev/jy8752/articles/351fc5d8c53029
# REF: https://cloud.google.com/workflows/docs/deploy-workflows-using-cloud-build
# REF: https://stackoverflow.com/questions/68779751/error-publishing-source-code-from-cloud-build-to-a-bucket-using-triggers
# REF: gcloud builds submit --config cloudbuild.yaml
steps:
  # frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --build-arg
      - PNPM_HOME=${_PNPM_HOME}
      - --build-arg
      - PNPM_PATH=${_PNPM_PATH}
      - --build-arg
      - CLIENT_PORT=${_CLIENT_PORT}
      - --build-arg
      - GRAPHQL_SCHEMA_URL=${_GRAPHQL_SCHEMA_URL}
      - -t
      - ${_FRONTEND_IMAGE}
      - ./frontend
    automapSubstitutions: true

substitutions:
  # general
  _REGION: _REGION
  # frontend
  _PNPM_HOME: _PNPM_HOME
  _PNPM_PATH: _PNPM_PATH
  _CLIENT_PORT: _CLIENT_PORT
  _GRAPHQL_SCHEMA_URL: _GRAPHQL_SCHEMA_URL
  _FRONTEND_IMAGE: _FRONTEND_IMAGE

options:
  logging: CLOUD_LOGGING_ONLY
